version: 2
registries:
  github-mfechio:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    registries:
      - github-mfechio
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
